drop table member if exists cascade;
create table member (
    id bigint generated by default as identity,
    username varchar(10),
    login_id varchar(10),
    password varchar(10),
    primary key (id)
);

drop table article if exists cascade;
create table article (
    id bigint generated by default as identity,
    create_by varchar(100),
    title varchar(100),
    author varchar(100),
    content varchar(255),
    upload_filename varchar(100),
    store_filename varchar(100),
    local_date_time varchar(100),
    primary key (id)
);