drop table member if exists cascade;
create table member (
    id bigint generated by default as identity,
    username varchar(10),
    login_id varchar(10),
    password varchar(10),
    primary key (id)
);